export const DEFAULT_CATEGORIES = [
  {
    id: "cat-1",
    name: "Skin Care",
    slug: "skin-care",
    description: "Herbal face oils, glowing serums, and natural botanical creams",
  },
  {
    id: "cat-2",
    name: "Hair Care",
    slug: "hair-care",
    description: "Pure hair growth oils, Ayurvedic shampoos, and scalp nourishers",
  },
  {
    id: "cat-3",
    name: "Pooja Items",
    slug: "pooja",
    description: "Traditional organic dhoop, herbal camphor, and brass pooja essentials",
  },
];

export const DEFAULT_PRODUCTS = [
  {
    id: "prod-1",
    name: "Kumkumadi Herbal Radiant Face Oil",
    slug: "kumkumadi-radiant-face-oil",
    price: 499,
    actual_price: 699,
    category: "Skin Care",
    description: "Infused with Kashmiri Saffron and 26 Ayurvedic herbs for glowing skin, deeply nourishing complexions and reducing dark spots.",
    image_url: "https://images.unsplash.com/photo-1608248597263-00079e96047c?auto=format&fit=crop&w=600&q=80",
    stock: 45,
    rating: 4.9,
    is_featured: true,
    is_active: true,
    is_returnable: true,
    return_period_days: 7,
  },
  {
    id: "prod-2",
    name: "Bhringraj & Neem Intensive Hair Growth Oil",
    slug: "bhringraj-neem-hair-oil",
    price: 389,
    actual_price: 499,
    category: "Hair Care",
    description: "Cold-pressed pure Sesame & Coconut oil infused with handpicked Bhringraj leaves to reduce hair loss and promote thick growth.",
    image_url: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=600&q=80",
    stock: 60,
    rating: 4.8,
    is_featured: true,
    is_active: true,
    is_returnable: true,
    return_period_days: 7,
  },
  {
    id: "prod-3",
    name: "Pure Sambrani Dhoop Cups (Pack of 12)",
    slug: "pure-sambrani-dhoop-cups",
    price: 199,
    actual_price: 299,
    category: "Pooja Items",
    description: "100% Organic natural tree resin dhoop cups for sacred rituals, purifying household air with uplifting herbal aromas.",
    image_url: "https://images.unsplash.com/photo-1602928321679-560bb453f190?auto=format&fit=crop&w=600&q=80",
    stock: 100,
    rating: 5.0,
    is_featured: true,
    is_active: true,
    is_returnable: false,
    return_period_days: 0,
  },
  {
    id: "prod-4",
    name: "Pure Organic Rose Water Hydrating Mist",
    slug: "organic-rose-water-mist",
    price: 249,
    actual_price: 349,
    category: "Skin Care",
    description: "Steam-distilled from Kannauj damask roses. Refreshes skin, tightens pores, and balances natural pH.",
    image_url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    stock: 30,
    rating: 4.7,
    is_featured: false,
    is_active: true,
    is_returnable: true,
    return_period_days: 5,
  },
  {
    id: "prod-5",
    name: "Amla & Hibiscus Natural Herbal Shampoo",
    slug: "amla-hibiscus-shampoo",
    price: 349,
    actual_price: 449,
    category: "Hair Care",
    description: "Sulfate-free revitalizing hair cleanser rich in Natural Vitamin C, leaving locks silky, soft, and bouncy.",
    image_url: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=600&q=80",
    stock: 25,
    rating: 4.8,
    is_featured: false,
    is_active: true,
    is_returnable: true,
    return_period_days: 7,
  },
  {
    id: "prod-6",
    name: "Organic Bhimseni Camphor (250g)",
    slug: "organic-bhimseni-camphor",
    price: 299,
    actual_price: 399,
    category: "Pooja Items",
    description: "100% Pure edible-grade crystal camphor. Crackles gently and leaves zero ash during aarti rituals.",
    image_url: "https://images.unsplash.com/photo-1615397349754-cfa2066a298e?auto=format&fit=crop&w=600&q=80",
    stock: 75,
    rating: 4.9,
    is_featured: false,
    is_active: true,
    is_returnable: false,
    return_period_days: 0,
  },
];

export const DEFAULT_OFFERS = [
  {
    id: "off-devora10",
    title: "10% Herbal Discount",
    description: "Flat 10% OFF on your entire Ayurvedic & botanical order",
    discountCode: "DEVORA10",
    type: "coupon",
    discountType: "percentage",
    discountValue: 10,
    discountPercent: 10,
    minOrderAmount: 0,
    maxDiscountCap: 0,
    usageLimit: 500,
    usageCount: 14,
    category: "All",
    isActive: true,
    showBanner: true,
    showProductPage: true,
    hasTimer: false,
  },
  {
    id: "off-flat100",
    title: "Flat ₹100 Mega Saver",
    description: "Save flat ₹100 on orders above ₹799",
    discountCode: "FLAT100",
    type: "coupon",
    discountType: "fixed",
    discountValue: 100,
    discountPercent: 0,
    minOrderAmount: 799,
    maxDiscountCap: 100,
    usageLimit: 200,
    usageCount: 8,
    category: "All",
    isActive: true,
    showBanner: false,
    showProductPage: true,
    hasTimer: false,
  },
  {
    id: "off-bogo",
    title: "Buy 2 Get 1 FREE",
    description: "Buy any 2 natural care items and get the 3rd item FREE",
    discountCode: "BUY2GET1",
    type: "bogo",
    discountType: "bogo",
    discountValue: 0,
    discountPercent: 0,
    minOrderAmount: 0,
    maxDiscountCap: 0,
    usageLimit: 300,
    usageCount: 22,
    category: "All",
    isActive: true,
    showBanner: true,
    showProductPage: true,
    hasTimer: false,
  },
  {
    id: "off-festive15",
    title: "Festive Celebration Savings",
    description: "Save 15% on pure natural wellness combos",
    discountCode: "FESTIVE15",
    type: "festival",
    discountType: "percentage",
    discountValue: 15,
    discountPercent: 15,
    minOrderAmount: 499,
    maxDiscountCap: 300,
    usageLimit: 150,
    usageCount: 45,
    category: "All",
    isActive: true,
    showBanner: true,
    showProductPage: true,
    hasTimer: true,
    timerEnd: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days from now
  },
  {
    id: "off-welcome10",
    title: "Welcome Gift Offer",
    description: "Get 10% off your entire first organic order",
    discountCode: "WELCOME10",
    type: "coupon",
    discountType: "percentage",
    discountValue: 10,
    discountPercent: 10,
    minOrderAmount: 299,
    maxDiscountCap: 0,
    usageLimit: 1000,
    usageCount: 31,
    category: "All",
    isActive: true,
    showBanner: false,
    showProductPage: true,
    hasTimer: false,
  },
];

export const DEFAULT_CUSTOMERS = [];

export const DEFAULT_ABOUT_DATA = {
  badge: "Our Ayurvedic Heritage",
  title: "Rooted in Nature, Crafted with Care",
  description: "Devora Naturals brings ancient botanical wisdom to modern self-care routines. Every bottle is lovingly formulated using wild-harvested herbs and traditional cold-press extraction.",
  cards: [
    {
      id: "about-1",
      title: "100% Pure Botanical Ingredients",
      description: "We source our Kashmiri saffron, Bhringraj leaves, and Kannauj roses directly from certified organic farms without artificial preservatives.",
      icon: "Sparkles",
    },
    {
      id: "about-2",
      title: "Traditional Small-Batch Formulations",
      description: "Following time-tested Ayurvedic taila-paka methods, our oils are slow-infused over copper vessels to preserve essential nutrients.",
      icon: "HeartHandshake",
    },
    {
      id: "about-3",
      title: "Ethical & Eco-Friendly Packaging",
      description: "All our products are cruelty-free, packaged in recyclable dark amber glass bottles to prevent UV oxidation.",
      icon: "ShieldCheck",
    },
  ],
};

export const DEFAULT_SOCIAL_LINKS = [
  {
    id: "soc-1",
    platform: "Instagram",
    title: "Instagram",
    url: "https://instagram.com/devoranaturals",
    icon: "Instagram",
    is_active: true,
  },
  {
    id: "soc-2",
    platform: "Facebook",
    title: "Facebook",
    url: "https://facebook.com/devoranaturals",
    icon: "Facebook",
    is_active: true,
  },
  {
    id: "soc-3",
    platform: "YouTube",
    title: "YouTube",
    url: "https://youtube.com/@devoranaturals",
    icon: "Youtube",
    is_active: true,
  },
  {
    id: "soc-4",
    platform: "WhatsApp",
    title: "WhatsApp Chat",
    url: "https://wa.me/918608540400",
    icon: "MessageCircle",
    is_active: true,
  },
];

export const DEFAULT_SETTINGS = {
  store_name: "Devora Naturals",
  tagline: "Pure Ayurvedic & Botanical Organic Care",
  email: "support@devoranaturals.com",
  phone: "+91 8608540400",
  address: "Kerala Botanical Organic Farm, India",
  whatsapp: "8608540400",
  free_shipping_threshold: 499,
  state_shipping_enabled: true,
  shipping_charge_tamilnadu: 50,
  shipping_charge_other_states: 100,
  standard_shipping_charge: 50,
  delivery_estimate: "Tamil Nadu: 1-2 Days | Other States: 3-5 Business Days",
  support_hours: "Mon - Sat: 9:00 AM - 7:00 PM IST",
  order_prefix: "DEV-",
  instagram_url: "https://instagram.com/devoranaturals",
  facebook_url: "https://facebook.com/devoranaturals",
  youtube_url: "https://youtube.com/@devoranaturals",
  social_links_enabled: true,
  social_links: DEFAULT_SOCIAL_LINKS,
  return_policy_enabled: true,
  return_window_days: 7,
  return_policy_text: "7-Day Easy Replacement Guarantee for damaged or defective items",
};

export const DEFAULT_ORDERS = [];

export const DEFAULT_STOREFRONT_SETTINGS = {
  // Store Identity & Customer Brand
  store_name: "Devora Naturals",
  tagline: "Pure Organic Botanical",
  logo_url: "",

  // Top Announcement Bar
  announcement_enabled: true,
  announcements: [
    {
      id: "ann-1",
      text: "Free Pan-India Express Delivery on Orders Above ₹499",
      highlight_text: "Free Delivery",
      link: "#products-section",
      is_active: true,
    },
    {
      id: "ann-2",
      text: "100% Pure Cold-Pressed Oils & Certified Ayurvedic Herbs",
      highlight_text: "Pure Ayurvedic",
      link: "/about",
      is_active: true,
    },
    {
      id: "ann-3",
      text: "Special Festive Launch: 15% OFF with code DEVORA15 at checkout",
      highlight_text: "15% OFF",
      link: "#products-section",
      is_active: true,
    },
  ],

  // Hero Section
  hero_badge: "Pure Organic & Ayurvedic Wellness",
  heroHeading: "Natural Care For Your Skin, Hair & Soul",
  heroDescription: "Elevate your daily self-care ritual with handcrafted Kumkumadi oils, wild-harvested Bhringraj scalp tonics, and sacred organic Sambrani dhoop.",
  hero_gradient_enabled: true,
  heroBgGradientStart: "#064e3b",
  heroBgGradientEnd: "#065f46",
  hero_primary_btn_text: "Explore Catalog",
  hero_primary_btn_link: "#products-section",
  hero_secondary_btn_text: "Our Botanical Story",
  hero_secondary_btn_link: "/about",

  // Bestseller & Hero Spotlight Cards (Add, Edit, Delete multiple cards)
  bestsellerEnabled: true,
  bestsellerTitle: "Kumkumadi Saffron Glow Oil",
  bestsellerSubtitle: "Bestseller",
  bestsellerPrice: "₹499",
  bestsellerImage: "https://images.unsplash.com/photo-1608248597263-00079e96047c?auto=format&fit=crop&w=800&q=80",
  bestsellerLink: "/products/prod-1",

  hero_cards_enabled: true,
  hero_cards: [
    {
      id: "hcard-1",
      title: "Kumkumadi Saffron Glow Oil",
      subtitle: "Bestseller",
      badge: "Kashmiri Saffron",
      price: "₹499",
      image_url: "https://images.unsplash.com/photo-1608248597263-00079e96047c?auto=format&fit=crop&w=800&q=80",
      link: "/products/prod-1",
      is_active: true,
    },
    {
      id: "hcard-2",
      title: "Bhringraj & Neem Hair Growth Oil",
      subtitle: "Trending Hair Vitalizer",
      badge: "Cold-Pressed Herbs",
      price: "₹389",
      image_url: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=800&q=80",
      link: "/products/prod-2",
      is_active: true,
    },
  ],

  // Value Propositions / Trust Pillars
  value_props_enabled: true,
  value_props: [
    {
      id: "vp-1",
      title: "100% Organic",
      description: "Pure wild-harvested botanical extracts",
      icon: "Leaf",
      is_active: true,
    },
    {
      id: "vp-2",
      title: "Chemical Free",
      description: "Zero sulfates, parabens, or mineral oils",
      icon: "ShieldCheck",
      is_active: true,
    },
    {
      id: "vp-3",
      title: "Handcrafted Batches",
      description: "Slow-infused in copper vessels",
      icon: "HeartHandshake",
      is_active: true,
    },
    {
      id: "vp-4",
      title: "Express Delivery",
      description: "Safe & prompt Pan-India doorstep delivery",
      icon: "Truck",
      is_active: true,
    },
  ],

  // Promotional Middle Banner & Featured Deals
  promoBannerEnabled: true,
  promoBannerTitle: "Handcrafted Botanical Elixirs for Ageless Beauty",
  promoBannerSubtitle: "Seasonal Harvest Edition",
  promoBannerImage: "https://images.unsplash.com/photo-1615397323282-311ab261291b?auto=format&fit=crop&w=1200&h=400&q=80",
  promoBannerBadge: "Limited Seasonal Deal",
  promoBannerLink: "#products-section",
  promoBannerBtnText: "Shop Botanical Collection",

  promos_list: [
    {
      id: "prm-1",
      title: "Ayurvedic Hair Vitalizer Combo",
      subtitle: "Pure Bhringraj, Neem & Hibiscus hair care system",
      badge: "Save 20%",
      image_url: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=800&q=80",
      link: "#products-section",
      button_text: "Shop Hair Care",
      is_active: true,
    },
    {
      id: "prm-2",
      title: "Sacred Pooja & Sambrani Dhoop",
      subtitle: "Traditional temple-grade organic incense & camphor",
      badge: "Aroma Therapy",
      image_url: "https://images.unsplash.com/photo-1602928321679-560bb453f190?auto=format&fit=crop&w=800&q=80",
      link: "#products-section",
      button_text: "Explore Pooja Essentials",
      is_active: true,
    },
  ],

  // Brand Spotlight / Why Choose Us
  spotlight_enabled: true,
  spotlight_badge: "The Devora Promise",
  spotlight_title: "Ethically Farmed & Handcrafted with Ancient Ayurvedic Wisdom",
  spotlight_description: "We bridge ancient Vedic recipes with modern cold-extraction science. Every droplet preserves active botanical phyto-nutrients, completely free of synthetics, parabens, and fillers.",
  spotlight_stat_1_val: "100%",
  spotlight_stat_1_lbl: "Pure Botanical Oils",
  spotlight_stat_2_val: "10,000+",
  spotlight_stat_2_lbl: "Happy Customers",
  spotlight_stat_3_val: "0%",
  spotlight_stat_3_lbl: "Parabens & Toxins",
  spotlight_stat_4_val: "4.9★",
  spotlight_stat_4_lbl: "Customer Rating",
  spotlight_image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80",

  // Testimonials / Customer Reviews
  testimonials_enabled: true,
  testimonials_title: "Loved by Thousands of Natural Beauty Enthusiasts",
  testimonials_subtitle: "Read authentic experiences from genuine buyers across India",
  testimonials: [
    {
      id: "test-1",
      customer_name: "Priya Nair",
      location: "Kochi, Kerala",
      rating: 5,
      comment: "The Kumkumadi oil has completely transformed my skin texture within 2 weeks. Zero breakouts and my natural glow is back!",
      product_name: "Kumkumadi Herbal Radiant Face Oil",
      image_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
      is_verified: true,
      is_active: true,
    },
    {
      id: "test-2",
      customer_name: "Aarav Sharma",
      location: "Bengaluru, Karnataka",
      rating: 5,
      comment: "Authentic Bhringraj aroma and true cold-pressed richness. Scalp feels deeply nourished and hair fall reduced dramatically in 3 weeks.",
      product_name: "Bhringraj & Neem Intensive Hair Oil",
      image_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
      is_verified: true,
      is_active: true,
    },
    {
      id: "test-3",
      customer_name: "Sneha Patel",
      location: "Ahmedabad, Gujarat",
      rating: 5,
      comment: "Smells divine! Organic camphor and dhoop make my morning meditation and pooja deeply peaceful. Won't buy anything else.",
      product_name: "Organic Bhimseni Camphor & Dhoop",
      image_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80",
      is_verified: true,
      is_active: true,
    },
  ],

  // Frequently Asked Questions (FAQ)
  faqs_enabled: true,
  faqs_title: "Frequently Asked Questions",
  faqs_subtitle: "Clear answers about our organic sourcing, usage, and policies",
  faqs: [
    {
      id: "faq-1",
      question: "Are Devora Naturals products 100% natural and chemical-free?",
      answer: "Yes, every single formula is handcrafted from wild-harvested herbs, cold-pressed plant oils, and botanical extracts with zero artificial preservatives, mineral oils, or sulfates.",
      category: "Ingredients",
      is_active: true,
    },
    {
      id: "faq-2",
      question: "How long does Pan-India shipping take?",
      answer: "Orders are packed and dispatched within 24 hours. Standard delivery arrives in 3-5 business days across all Indian states.",
      category: "Shipping",
      is_active: true,
    },
    {
      id: "faq-3",
      question: "What is your return & replacement policy?",
      answer: "We provide an easy 7-day doorstep replacement guarantee for any damaged, leaking, or defective products received.",
      category: "Returns",
      is_active: true,
    },
    {
      id: "faq-4",
      question: "Can I use Kumkumadi oil on oily or sensitive skin?",
      answer: "Kumkumadi tailam is formulated as a light, non-comedogenic tridoshic oil. For oily skin, apply 2-3 drops at night on a cleansed face and massage gently until absorbed.",
      category: "Usage",
      is_active: true,
    },
  ],

  // Customer Navbar Settings & Navigation Links
  navbar: {
    sticky: true,
    show_cart: true,
    show_account: true,
    show_categories: true,
    cart_label: "Cart",
    account_label: "Account",
    custom_links: [
      { id: "nav-1", name: "Home", href: "/", is_active: true },
      { id: "nav-2", name: "All Products", href: "/products", is_active: true },
      { id: "nav-3", name: "About Us", href: "/about", is_active: true },
      { id: "nav-4", name: "Contact", href: "/contact", is_active: true },
    ],
  },

  // Customer Footer Settings, Columns & Links
  footer: {
    description: "Crafting pure, organic herbal products deeply rooted in Ayurvedic heritage. Dedicated to your wellness, radiant skin, and authentic traditional rituals.",
    show_social_links: true,
    social_heading: "Follow Us Online",

    // Column 1: Categories / Custom Menu
    col1_heading: "Categories",
    col1_show_dynamic_categories: true,
    col1_links: [
      { id: "fcol1-1", label: "Skin Care Essentials", href: "/products?category=Skin Care", is_active: true },
      { id: "fcol1-2", label: "Ayurvedic Hair Oils", href: "/products?category=Hair Care", is_active: true },
      { id: "fcol1-3", label: "Sacred Pooja Dhoop & Resins", href: "/products?category=Pooja Items", is_active: true },
      { id: "fcol1-4", label: "View Full Catalog", href: "/products", is_active: true },
    ],

    // Column 2: Devora Naturals / Quick Links
    col2_heading: "Devora Naturals",
    col2_links: [
      { id: "fcol2-1", label: "About Our Brand", href: "/about", is_active: true },
      { id: "fcol2-2", label: "Contact & Support", href: "/contact", is_active: true },
      { id: "fcol2-3", label: "Customer Account", href: "/account", is_active: true },
    ],

    // Column 3: Contact Details display toggles
    col3_heading: "Contact Us",
    show_contact_email: true,
    show_contact_phone: true,
    show_contact_address: true,
    show_social_badges: true,

    // Bottom Bar
    copyright_text: "Devora Naturals. All Rights Reserved.",
    badge_text: "Handcrafted with ❤️ for natural wellness",
    show_bottom_badge: true,
  },
};

